# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import PageServer_pb2 as PageServer__pb2


class PageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.announce = channel.unary_unary(
                '/Page/announce',
                request_serializer=PageServer__pb2.AnnounceRequest.SerializeToString,
                response_deserializer=PageServer__pb2.Response.FromString,
                )
        self.findKey = channel.unary_unary(
                '/Page/findKey',
                request_serializer=PageServer__pb2.FindRequest.SerializeToString,
                response_deserializer=PageServer__pb2.FindResponse.FromString,
                )


class PageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def announce(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def findKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'announce': grpc.unary_unary_rpc_method_handler(
                    servicer.announce,
                    request_deserializer=PageServer__pb2.AnnounceRequest.FromString,
                    response_serializer=PageServer__pb2.Response.SerializeToString,
            ),
            'findKey': grpc.unary_unary_rpc_method_handler(
                    servicer.findKey,
                    request_deserializer=PageServer__pb2.FindRequest.FromString,
                    response_serializer=PageServer__pb2.FindResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Page', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Page(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def announce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Page/announce',
            PageServer__pb2.AnnounceRequest.SerializeToString,
            PageServer__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def findKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Page/findKey',
            PageServer__pb2.FindRequest.SerializeToString,
            PageServer__pb2.FindResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
